services:
  sti-cds-service:
    container_name: sti-cds-service
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      FHIR_TERMINOLOGY_SERVER_URL: https://fhir-test-terminology.com/baseR4
      HIV_FHIR_SERVER_FILTER: ""

