services:
  sti-cds-service:
    container_name: sti-cds-service
    image: 435911253355.dkr.ecr.us-west-2.amazonaws.com/sti-cds-service:2944156a6251185def2cedfe5c8c3e1ba39d5c06
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      CONFIG_CLIENT_ID: config-api
      CONFIG_GRANT_TYPE: password
      CONFIG_PASSWORD: $CONFIG_PASSWORD
      CONFIG_SCOPE: openid
      CONFIG_USERNAME: omnibus
      CONFIG-CLIENT-SECRET: asdf
      AUTH_SERVER_URL: https://auth-internal.elimuinformatics.com/auth/realms/product
      ENVIRONMENT: dev
      FHIR_GRANT_TYPE: password
      FHIR_PASSWORD: $CONFIG_PASSWORD
      FHIR_CLIENT_ID: fhir4-api
      FHIR_USERNAME: omnibus
      FHIR_SCOPE: openid
      FHIR_CLIENT_SECRET: openid
      VALID_AUD_LIST: ""
      VALID_ISS_LIST: ""
      VALID_PRESET_KEYS_LIST: ""
      VALID_JKU_LIST: ""
      FHIR_SERVER_URL: https://fhir4-internal.elimuinformatics.com/fhir
      FHIR_TERMINOLOGY_SERVER_URL: https://fhir4-terminology-sandbox-internal.elimuinformatics.com/baseR4
      HIV_FHIR_SERVER_FILTER: ""
      KBASE_NAME: gc_sti_cdshoooks

