server:
  address: 0.0.0.0
kogito:
  service:
    url: http://localhost:8080
quarkus:
  log:
    console:
      json:
        pretty-print: false
      format: '%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) <%X{x-correlation-id}> %s%e%n'
    min-level: DEBUG
    category:
      io.elimu:
        level: DEBUG
  http:
    auth:
      permission:
        authenticated:
          paths:  /*
          policy: permit
            #authenticated
        public:
          paths: /q/health/*, /q/metrics/*
          policy: permit
  oidc:
    tenant-enabled: false
  kogito:
    devservices:
      enabled: false

io:
  elimu:
    log-scrubber:
      values:
        - (?i)(patient.*?([-=:]|\":)(.*?\b))(?:.*?[^ms]\S)(?:(\s+,|,|\")|$)
        - (?i)(encounter.*?([-=:]|\":)(.*?\b))(?:.*?[^ms]\S)(?:(\s+,|,|\")|$)
        - (?i)(refresh_token.*?([-=:]|\":)(.*?\b))(?:.*?\S)(?:(\s+,|,|\")|$)
        - (?i)(id_token.*?([-=:]|\":)(.*?\b))(?:.*?\S)(?:(\s+,|,|\")|$)
        - (?i)(access_token.*?([-=:]|\":)(.*?\b))(?:.*?\S)(?:(\s+,|,|\")|$)
        - (?i)(\bauthorization.*?([-=:]|\":)(.*?\b))(?:.*?\S)(?:(\s+,|,|\")|$)
        - (?i)(\bfhir_authorization.*?([-=:]|\":)(.*?\b))(?:.*?\S)(?:(\s+,|,|\")|$)
        - (?i)(password.*?([-=:]|\":)(.*?\b))(?:.*?\S)(?:(\s+,|,|\")|$)
      mask: $1****$4

'%dev':
  quarkus:
    log:
      console:
        json: false
        format: '%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) <%X{x-correlation-id}> %s%e%n'

configs:
  procvar:
    outputType: application/json
    jwtValidAud: ${VALID_AUD_LIST}
    jwtValidIss: ${VALID_ISS_LIST}
    jwtValidPresetKeys: ${VALID_PRESET_KEYS_LIST}
    jwtValidJku: ${VALID_JKU_LIST}
    fhirTerminologyServerUrl: ${FHIR_TERMINOLOGY_SERVER_URL}
    organizationsHivFiltered: ${HIV_FHIR_SERVER_FILTER}
discovery:
  confirmed_gc_treatment:
    id: confirmed_gc_treatment
    title: 'CDS for Confirmed Treatment of Gonorrhea'
    description: 'CDS for confirmed treatment of gonorrhea'
    hook: 'patient-view'
    prefetch:
      patient: 'Patient/{{context.patientId}}'
  presumptive_gc_treatment:
   id: presumptive_gc_treatment,
   title: 'CDS for Presumptive Treatment of Gonorrhea'
   description: 'CDS for presumptive treatment of gonorrhea - Ceftriaxone dose check, chlamydia treatment, partner treatment, HIV screening'
   hook: 'order-sign'
   prefetch:
     patient: 'Patient/{{context.patientId}}'
